# Generated by Django 3.2.4 on 2021-07-08 15:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210707_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sci-fi', 'Sci-fi'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Fiction', 'Fiction'), ('Biography', 'Biography'), ('Adventure', 'Adventure')], max_length=49),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Hindi', 'Hindi')], default='eng', max_length=100),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
