# Generated by Django 3.2.4 on 2021-07-08 17:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210708_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Hindi', 'Hindi')], default='English', max_length=35),
        ),
    ]
